---
kind: pipeline
type: docker
name: build & deploy

# workspace:
#   path: /drone/src

platform:
  os: linux
  arch: amd64

steps:
  - name: build amd64
    image: plugins/docker
    environment:
      BUILDPLATFORM: linux/amd64
      TARGETPLATFORM: linux/amd64
    settings:
      repo: quay.io/wasilak/cloudpile-test
      registry: quay.io
      auto_tag: true
      auto_tag_suffix: linux-amd64
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

      build_args_from_env:
        - BUILDPLATFORM
        - TARGETPLATFORM
    when:
      event: tag

  - name: build arm64
    image: plugins/docker
    environment:
      BUILDPLATFORM: linux/arm64
      TARGETPLATFORM: linux/arm64
    settings:
      repo: quay.io/wasilak/cloudpile-test
      registry: quay.io
      auto_tag: true
      auto_tag_suffix: linux-arm64
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

      build_args_from_env:
        - BUILDPLATFORM
        - TARGETPLATFORM
    when:
      event: tag

  - name: build arm7
    image: plugins/docker
    environment:
      BUILDPLATFORM: linux/arm/v7
      TARGETPLATFORM: linux/arm/v7
    settings:
      repo: quay.io/wasilak/cloudpile-test
      registry: quay.io
      auto_tag: true
      auto_tag_suffix: linux-arm7
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

      build_args_from_env:
        - BUILDPLATFORM
        - TARGETPLATFORM
    when:
      event: tag

  - name: manifest
    image: plugins/manifest
    settings:
      auto_tag: true
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      spec: .drone-manifest.tmpl
      ignore_missing: true
    when:
      event: tag
    depends_on:
      - build amd64
      - build arm64
      - build arm7
