---
kind: pipeline
type: docker
name: build & deploy

# workspace:
#   path: /drone/src

platform:
  os: linux
  arch: amd64

steps:
  # - name: linux amd64
  #   image: quay.io/wasilak/golang:1.16-alpine
  #   pull: if-not-exists
  #   environment:
  #     GOOS: linux
  #     GOARCH: amd64
  #   commands:
  #     - go build -o dist/cloudflare-ddns-$${GOOS}-$${GOARCH}

  - name: build amd64
    image: plugins/docker
    settings:
      repo: quay.io/wasilak/cloudpile-test
      # auto_tag: true
      insecure: true
      tags:
        - latest
        - "1.0.0"
      auto_tag_suffix: "-amd64"
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

  - name: manifest
    image: plugins/manifest
    settings:
      tags:
        - latest
        - "1.0.0"
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      # spec: drone-manifest.tmpl
      target: quay.io/wasilak/cloudpile-test:1.0.0
      template: quay.io/wasilak/cloudpile-test:1.0.0-OS-ARCH
      platforms:
        - linux/amd64
        # - linux/arm
        # - linux/arm64
    # depends_on:
    #   - osx amd64
    #   - linux amd64
    #   - linux armv7
    #   - linux arm64
